// Compute shader for updating particles
#version 430 core
layout(local_size_x = 256) in;

// Changed to Structure of Arrays
layout(std430, binding = 1) buffer Positions {
    vec4 positions[];
};

layout(std430, binding = 2) buffer Velocities {
    vec4 velocities[];
};

layout(std430, binding = 3) buffer ColorBegin {
    vec4 colorBegins[];
};

layout(std430, binding = 4) buffer ColorEnds {
    vec4 colorEnds[];
};

layout(std430, binding = 0) buffer FreeListBuffer {
    int count;
    int indices[];
} freelist;

// Atomic counter for counting active particles
layout(binding = 1, offset = 0) uniform atomic_uint activeParticleCount;

uniform float deltaTime;
uniform vec3 globalForce;
uniform float sizeBegin;
uniform float sizeEnd;

void UpdateParticle(int index)
{
    // Update life
   velocities[index].w -= deltaTime;
    
    // If particle just died, add to free list and return
    if (velocities[index].w <= 0.0) 
    {
        int idx = atomicAdd(freelist.count, 1);
        freelist.indices[idx] = index;
        return;
    }

    // Count this as an active particle
    atomicCounterIncrement(activeParticleCount);
    
    // Apply global force to velocity
    velocities[index].xyz += globalForce * deltaTime;
    
    // Update position based on velocity
    positions[index].xyz += velocities[index].xyz * deltaTime;
    
    // Calculate life percentage
    float lifespan = colorEnds[index].w;
    float lifeRemaining = velocities[index].w;
    float lifePercent = lifeRemaining / lifespan;
    
    // Update size based on life
    positions[index].w = mix(sizeEnd, sizeBegin, lifePercent);
}

void main()
{
    uint id = gl_GlobalInvocationID.x;
    
    // Check if we're in bounds
    if (id >= positions.length())
        return;

    if (velocities[id].w <= 0.0)
        return;

    UpdateParticle(int(id));
}